"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { atlasComponents, atlasDecisionsV2, atlasSectionNav, fieldNotes, limitationsV2 } from "../data/atlasV2";

type ComponentId = keyof typeof atlasComponents;
type Lens = "system" | "ingestion" | "search" | "decisions" | "validation" | "field-notes" | "build-record";

const lensLinks: [string, Lens, string][] = [["SYSTEM","system","system"],["DECISIONS","decisions","decision-trail"],["VALIDATION","validation","validation"],["FIELD NOTES","field-notes","field-notes"],["BUILD RECORD","build-record","build-record"]];

function RelatedLinks({ items }: { items: readonly string[] }) {
  const href = (item:string) => item.startsWith("EVD-") ? `#${item.toLowerCase()}` : item.startsWith("D-") ? `#${item.toLowerCase()}` : item.startsWith("FN-") ? `#${item.toLowerCase()}` : item.startsWith("Milestone") ? "#build-record" : `#${item}`;
  return <div className="atlas-related">{items.map(item=><a key={item} href={href(item)}>{item}</a>)}</div>;
}

export default function AtlasProjectExplorer({ evidence }: { evidence: React.ReactNode }) {
  const [selected,setSelected]=useState<ComponentId>("indexer");
  const [lens,setLens]=useState<Lens>("system");
  const [current,setCurrent]=useState("current-state");
  const component=atlasComponents[selected];
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setCurrent(visible.target.id);},{rootMargin:"-15% 0px -70%",threshold:[0,.2,.6]});atlasSectionNav.forEach(([, ,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);
  const traceClass = lens === "ingestion" ? "trace-ingestion" : lens === "search" ? "trace-search" : `lens-${lens}`;
  const node=(id:ComponentId,label:string,sub:string)=><button type="button" className={`atlas-v2-node node-${id} ${selected===id?"is-selected":""}`} onClick={()=>setSelected(id)} aria-pressed={selected===id}><span>{label}</span><strong>{atlasComponents[id].name}</strong><small>{sub}</small><em>● VALIDATED</em></button>;

  return <main className="atlas-v2">
    <aside className="atlas-v2-index" aria-label="Project Atlas index"><div><Link href="/">RESUMEOPS / J.A.</Link><p>PROJECT ATLAS</p><span>● ACTIVE</span></div><nav><ol>{atlasSectionNav.map(([n,label,id])=><li key={id}><a href={`#${id}`} aria-current={current===id?"location":undefined}><b>{n}</b>{label}</a></li>)}</ol></nav></aside>
    <div className="atlas-v2-main">
      <section id="current-state" className="atlas-v2-current atlas-v2-section"><p className="atlas-v2-kicker">PROJECTS / ATLAS</p><div className="atlas-v2-current-grid"><div><h1>PROJECT ATLAS</h1><p className="atlas-v2-subtitle">TECHNICAL PROVING GROUND</p><p>A distributed Splunk environment used to rebuild, extend, and publicly validate hands-on engineering knowledge.</p></div><dl><div><dt>STATUS</dt><dd className="state-value">ACTIVE</dd></div><div><dt>CURRENT CHECKPOINT</dt><dd>04</dd></div><div><dt>LATEST CAPABILITY</dt><dd>Windows Event Ingestion</dd></div><div><dt>RUNTIME</dt><dd>Splunk Enterprise 10.0.8</dd></div><div><dt>ENVIRONMENT</dt><dd>Windows + Docker</dd></div><div><dt>VALIDATION</dt><dd className="state-value">VALIDATED</dd></div><div><dt>UPDATED</dt><dd>2026-08-12</dd></div><div><dt>SOURCE</dt><dd><a href="https://github.com/jannsenagustin/resumeops">GitHub</a></dd></div></dl></div><div className="atlas-method"><span>METHOD</span><strong>BUILD <i>→</i> VALIDATE <i>→</i> EXPLAIN</strong></div></section>
      <div className="atlas-v2-lenses" aria-label="Investigation lenses">{lensLinks.map(([label,value,target])=><button key={label} type="button" aria-pressed={lens===value} onClick={()=>{setLens(value);if(target!=="system")document.getElementById(target)?.scrollIntoView()}}>{label}</button>)}</div>
      <section id="system" className="atlas-v2-section"><header><p>01 / SYSTEM</p><h2>Atlas system architecture</h2><span>Inspect a component or trace a validated relationship.</span></header><div className={`atlas-v2-system ${traceClass}`}>
        <div className="atlas-v2-diagram"><div className="atlas-v2-boundary host"><label>WINDOWS HOST / JNNSN</label>{node("logs","EVENT SOURCES","Application · Security · System")}<i>→</i>{node("forwarder","HOST SERVICE","Universal Forwarder 10.0.8")}</div><button className="atlas-v2-path path-ingestion" onClick={()=>setSelected("boundary")} aria-label="Inspect host and container boundary">127.0.0.1:9997 →</button><div className="atlas-v2-boundary docker"><label>DOCKER / ATLAS-NETWORK</label>{node("indexer","CONTAINER","Receiver · Search peer")}<button className="atlas-v2-path path-search" onClick={()=>setSelected("management")} aria-label="Inspect distributed search relationship">⇄<small>HTTPS / TCP 8089</small></button>{node("searchHead","CONTAINER","Search coordinator")}</div><button className="atlas-storage" onClick={()=>setSelected("storage")}>NAMED STORAGE / etc + var per role</button></div>
        <aside className="atlas-v2-inspector" aria-live="polite"><p>COMPONENT INSPECTOR</p><h3>{component.name}</h3><span>ROLE</span><p>{component.role}</p><dl>{component.metadata.map(([k,v])=><div key={k}><dt>{k}</dt><dd className={k==="STATE"?"state-value":""}>{v}</dd></div>)}</dl><span>RELATED</span><RelatedLinks items={component.related}/></aside>
      </div><div className="atlas-trace-controls"><button onClick={()=>setLens("system")} aria-pressed={lens==="system"}>SYSTEM</button><button onClick={()=>setLens("ingestion")} aria-pressed={lens==="ingestion"}>TRACE INGESTION</button><button onClick={()=>setLens("search")} aria-pressed={lens==="search"}>TRACE DISTRIBUTED SEARCH</button></div><p className="sr-only">Windows Event Logs flow through Universal Forwarder on JNNSN to 127.0.0.1:9997 and atlas-indexer:9997. atlas-search-head coordinates distributed search with atlas-indexer over HTTPS port 8089 on atlas-network.</p></section>
      <section id="decision-trail" className="atlas-v2-section atlas-record-section"><header><p>02 / DECISION TRAIL</p><h2>Why Atlas was built this way</h2><span>Page-specific decision IDs cross-link architecture, proof, and troubleshooting.</span></header><div className="decision-trail">{atlasDecisionsV2.map(d=><article id={d.id.toLowerCase()} key={d.id}><div><b>{d.id}</b><h3>{d.title}</h3></div><dl><div><dt>CONTEXT</dt><dd>{d.context}</dd></div><div><dt>DECISION</dt><dd>{d.decision}</dd></div><div><dt>RATIONALE</dt><dd>{d.rationale}</dd></div>{"tradeoff" in d&&<div><dt>TRADE-OFF</dt><dd>{d.tradeoff}</dd></div>}{"validation" in d&&<div><dt>VALIDATION</dt><dd>{d.validation}</dd></div>}</dl><RelatedLinks items={d.related}/></article>)}</div></section>
      <section id="validation" className="atlas-v2-section atlas-record-section"><header><p>03 / VALIDATION</p><h2>Claims connected to proof</h2><span>Captured results are point-in-time observations, not live metrics.</span></header><div className="validation-chains"><article><b>MILESTONE 03</b><h3>Distributed Search</h3><ol><li>Search peer configured</li><li>Peer captured Up / Healthy / Enabled</li><li>Metadata search returned Indexer-associated data</li><li>Job Inspector showed dispatch.stream.remote.atlas-indexer</li></ol><RelatedLinks items={["D-007","EVD-03-01","EVD-03-03"]}/></article><article><b>MILESTONE 04</b><h3>Windows Event Ingestion via Universal Forwarder</h3><ol><li>SplunkForwarder service running</li><li>Windows reached TCP 9997</li><li>127.0.0.1:9997 listed under active forwards</li><li>Application, Security, and System logs searchable</li><li>Job Inspector confirmed remote Indexer execution</li></ol><RelatedLinks items={["D-005","FN-004","EVD-04-03","EVD-04-05"]}/></article></div><div className="evidence-exhibits">{evidence}</div></section>
      <section id="build-record" className="atlas-v2-section atlas-record-section"><header><p>04 / BUILD RECORD</p><h2>Four validated milestones</h2><span>Atlas evolves by adding one testable system capability at a time.</span></header><ol className="build-record"><li><b>01</b><div><h3>Indexer Deployment</h3><p>Established the first containerized Splunk role with persistent storage and verified Web access.</p><span>COMPLETE / VALIDATED · 4 artifacts</span></div></li><li><b>02</b><div><h3>Search Head Deployment</h3><p>Added an independently persisted Search Head on atlas-network.</p><span>COMPLETE / VALIDATED · 4 artifacts</span></div></li><li><b>03</b><div><h3>Distributed Search</h3><p>Connected Search Head and Indexer over HTTPS/8089 and proved remote execution.</p><span>COMPLETE / VALIDATED · 3 public artifacts</span></div></li><li><b>04</b><div><h3>Windows Event Ingestion via Universal Forwarder</h3><p>Installed UF on Windows, selected three Event Log inputs, configured direct forwarding, resolved inactive forwarding, and proved end-to-end search.</p><span>COMPLETE / VALIDATED · 5 artifacts</span><RelatedLinks items={["D-004","D-005","FN-004","EVD-04-05"]}/></div></li></ol></section>
      <section id="field-notes" className="atlas-v2-section atlas-record-section"><header><p>05 / FIELD NOTES</p><h2>Troubleshooting record</h2><span>Concise operational lessons; full detail remains in the engineering journals.</span></header><div className="field-notes">{fieldNotes.map(n=><article id={n.id.toLowerCase()} key={n.id}><b>{n.id} · RESOLVED</b><h3>{n.title}</h3><dl><div><dt>OBSERVED</dt><dd>{n.observed}</dd></div><div><dt>CAUSE</dt><dd>{n.cause}</dd></div><div><dt>RESOLUTION</dt><dd>{n.resolution}</dd></div><div><dt>LESSON</dt><dd>{n.lesson}</dd></div></dl><RelatedLinks items={n.related}/></article>)}</div></section>
      <section id="limitations" className="atlas-v2-section atlas-record-section"><header><p>06 / LIMITATIONS</p><h2>Explicit system boundaries</h2><span>Planned and exploratory work is not presented as implemented.</span></header><dl className="limitations-list">{limitationsV2.map(([name,state])=><div key={name}><dt>{name}</dt><dd>{state}</dd></div>)}</dl></section>
      <section id="source-of-truth" className="atlas-v2-section atlas-source"><p>07 / SOURCE OF TRUTH</p><h2>Independent verification starts with the repository.</h2><p>Atlas is documented publicly through source, configuration, architecture records, engineering journals, evidence, and commit history.</p><ul><li>Infrastructure</li><li>Architecture documentation</li><li>Engineering journal</li><li>Milestone records</li><li>Evidence artifacts</li><li>Configuration and Git history</li></ul><a href="https://github.com/jannsenagustin/resumeops" target="_blank" rel="noopener noreferrer">EXPLORE REPOSITORY →</a></section>
    </div>
  </main>;
}
