"use client";

import { useEffect, useState } from "react";
import ConsoleIcon, { type ConsoleIconName } from "./ConsoleIcon";
import AtlasNavigation from "./AtlasNavigation";
import ResumeViewer from "./ResumeViewer";
import ResumeViewerTrigger from "./ResumeViewerTrigger";
import TelemetryFlow from "./TelemetryFlow";
import { managementPath } from "../data/homeConsole";
import { atlasComponents, atlasDecisionsV2, atlasSectionNav, fieldNotes, limitationsV2 } from "../data/atlasV2";
import type { AtlasProjectState } from "../lib/atlasMilestoneTypes";

type ComponentId = keyof typeof atlasComponents;
type Lens = "system" | "ingestion" | "search" | "decisions" | "validation" | "field-notes" | "milestones";

const lensLinks: [string, Lens, string][] = [["MILESTONES","milestones","milestones"],["SYSTEM","system","system"],["DECISIONS","decisions","decision-trail"],["VALIDATION","validation","validation"],["FIELD NOTES","field-notes","field-notes"]];
const atlasNavIcons: ConsoleIconName[] = ["activity", "flag", "network", "file", "evidence", "file", "activity", "repository"];
const lensIcons: Record<Lens, ConsoleIconName> = { milestones:"flag", system:"server", ingestion:"transfer", search:"search", decisions:"file", validation:"evidence", "field-notes":"file" };
const validatedMilestones = [
  { id:"01", title:"Containerized Splunk Foundation", steps:["Compose configuration resolved","atlas-indexer captured healthy","Docker runtime captured","Administrator login confirmed"], related:["EVD-01-02","EVD-01-04"] },
  { id:"02", title:"Search Head Deployment", steps:["Search Head and Indexer captured healthy","Search Head login confirmed","Multi-service runtime captured","Shared atlas-network membership confirmed"], related:["EVD-02-01","EVD-02-03"] },
  { id:"03", title:"Distributed Search", steps:["Search peer configured","Peer captured Up / Healthy / Enabled","Metadata search returned Indexer-associated data","Job Inspector showed dispatch.stream.remote.atlas-indexer"], related:["D-007","EVD-03-01","EVD-03-03"] },
  { id:"04", title:"Windows Event Ingestion via Universal Forwarder", steps:["SplunkForwarder service running","Windows reached TCP 9997","127.0.0.1:9997 listed under active forwards","Application, Security, and System logs searchable","Job Inspector confirmed remote Indexer execution"], related:["D-005","FN-004","EVD-04-03","EVD-04-05"] },
] as const;

function RelatedLinks({ items }: { items: readonly string[] }) {
  const href = (item:string) => item.startsWith("EVD-") ? `#${item.toLowerCase()}` : item.startsWith("D-") ? `#${item.toLowerCase()}` : item.startsWith("FN-") ? `#${item.toLowerCase()}` : item.startsWith("Milestone") ? "#milestones" : `#${item}`;
  return <div className="atlas-related">{items.map(item=><a key={item} href={href(item)}>{item}</a>)}</div>;
}

export default function AtlasProjectExplorer({ evidence, projectState }: { evidence: React.ReactNode; projectState: AtlasProjectState }) {
  const publicMilestones = projectState.milestones.filter((milestone) => Number(milestone.number) <= 5);
  const validationMilestones = [...validatedMilestones, {
    id: projectState.currentMilestone.number,
    title: projectState.currentMilestone.title,
    steps: [
      ...projectState.currentDetail.completedFoundation.map((item) => `Completed foundation: ${item}`),
      ...projectState.activeTasks.map((task) => `Active: ${projectState.activeBatch.id} / ${task.id} — ${task.title}`),
      `Current boundary: ${projectState.currentBoundary}`,
    ],
    related: ["limitations"],
    planned: true,
  }];
  const [selected,setSelected]=useState<ComponentId>("indexer");
  const [lens,setLens]=useState<Lens>("system");
  const [current,setCurrent]=useState("current-state");
  const component=atlasComponents[selected];
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setCurrent(visible.target.id);},{rootMargin:"-15% 0px -70%",threshold:[0,.2,.6]});atlasSectionNav.forEach(([, ,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);
  const traceClass = lens === "ingestion" ? "trace-ingestion" : lens === "search" ? "trace-search" : `lens-${lens}`;
  const node=(id:ComponentId,label:string,sub:string)=><button type="button" className={`atlas-v2-node node-${id} ${selected===id?"is-selected":""}`} onClick={()=>setSelected(id)} aria-pressed={selected===id}><span>{label}</span><strong>{atlasComponents[id].name}</strong><small>{sub}</small><em>● VALIDATED</em></button>;

  return <><main id="atlas-console-shell" className="atlas-v2">
    <aside className="atlas-v2-index" aria-label="Project Atlas index"><div><strong>PROJECT ATLAS / J.A.</strong><p>ENGINEERING CONSOLE</p><span className="atlas-status atlas-status--active">ACTIVE</span></div><AtlasNavigation active="atlas" /><nav aria-label="Atlas page sections"><ol>{atlasSectionNav.map(([n,label,id],index)=><li key={id}><a className="console-icon-link console-icon-link--indexed" href={`#${id}`} aria-current={current===id?"location":undefined}><b>{n}</b><ConsoleIcon name={atlasNavIcons[index]} /><span className="console-label">{label}</span></a></li>)}</ol></nav><div className="atlas-v2-index-actions"><ResumeViewerTrigger className="console-icon-link"><ConsoleIcon name="resume" /><span className="console-label">View Professional Resume</span></ResumeViewerTrigger><a className="console-icon-link" href="https://github.com/jannsenagustin/resumeops" target="_blank" rel="noopener noreferrer"><ConsoleIcon name="repository" /><span className="console-label">Repository</span></a></div></aside>
    <div className="atlas-v2-main">
      <section id="current-state" className="atlas-v2-current atlas-v2-section"><p className="atlas-v2-kicker">PROJECTS / ATLAS</p><div className="atlas-v2-current-grid"><div><h1>PROJECT ATLAS</h1><p className="atlas-v2-subtitle">TECHNICAL PROVING GROUND</p><p>A distributed Splunk environment used to rebuild, extend, and publicly validate hands-on engineering knowledge.</p></div><dl><div><dt>STATUS</dt><dd className="state-value">{projectState.currentMilestone.status}</dd></div><div><dt>CURRENT CHECKPOINT</dt><dd>{projectState.currentMilestone.number}</dd></div><div><dt>CURRENT PHASE</dt><dd>{projectState.currentDetail.currentPhase}</dd></div><div><dt>ACTIVE BATCH</dt><dd>{projectState.activeBatch.id}</dd></div><div><dt>ACTIVE OBJECTIVE</dt><dd>{projectState.activeTasks[0]?.id ?? "Awaiting approval"}</dd></div><div><dt>VALIDATION</dt><dd className="state-value">{projectState.currentMilestone.validationState}</dd></div><div><dt>SOURCE</dt><dd><a href="https://github.com/jannsenagustin/resumeops/blob/main/docs/milestones.md">Milestones</a></dd></div></dl></div><div className="atlas-method"><span>METHOD</span><strong>BUILD <i>→</i> VALIDATE <i>→</i> EXPLAIN</strong></div></section>
      <div className="atlas-v2-lenses" aria-label="Investigation lenses">{lensLinks.map(([label,value,target])=><button className="console-icon-link" key={label} type="button" aria-pressed={lens===value} onClick={()=>{setLens(value);if(target!=="system")document.getElementById(target)?.scrollIntoView()}}><ConsoleIcon name={lensIcons[value]} /><span className="console-label">{label}</span></button>)}</div>
      <section id="milestones" className="atlas-v2-section atlas-record-section"><header><p>01 / MILESTONES</p><h2>Engineering evolution from foundation to telemetry</h2><span>Each validated capability created the prerequisite for the next.</span></header><ol className="build-record">{publicMilestones.map(milestone=><li key={milestone.id}><b>{milestone.number}</b><div><h3>{milestone.title}</h3><p>{milestone.outcome}</p><span>{milestone.status.toUpperCase()} / {milestone.validationState.toUpperCase()}</span></div></li>)}</ol></section>
      <section id="system" className="atlas-v2-section"><header><p>02 / SYSTEM</p><h2>Atlas system architecture</h2><span>Inspect a component or trace a validated relationship.</span></header><div className={`atlas-v2-system ${traceClass}`}>
        <div className="atlas-v2-diagram"><div className="atlas-v2-boundary host"><label>WINDOWS HOST / JNNSN</label>{node("logs","EVENT SOURCES","Application · Security · System")}<i>→</i>{node("forwarder","HOST SERVICE","Universal Forwarder 10.0.8")}</div><button className="atlas-v2-path path-ingestion" onClick={()=>setSelected("boundary")} aria-label="Inspect host and container boundary">127.0.0.1:9997 →</button><div className="atlas-v2-boundary docker"><label>DOCKER / ATLAS-NETWORK</label>{node("indexer","CONTAINER","Receiver · Search peer")}<button className="atlas-v2-path path-search" onClick={()=>setSelected("management")} aria-label="Inspect distributed search relationship">⇄<small>HTTPS / TCP 8089</small></button>{node("searchHead","CONTAINER","Search coordinator")}</div><button className="atlas-storage" onClick={()=>setSelected("storage")}>NAMED STORAGE / etc + var per role</button><p className="atlas-telemetry-caption">DOCUMENTED INGESTION PATH <strong>VALIDATED</strong></p><TelemetryFlow className="atlas-telemetry-flow" /></div>
        <aside className="atlas-v2-inspector" aria-live="polite"><header><p>COMPONENT INSPECTOR</p><h3>{component.name}</h3></header><div className="atlas-v2-inspector__body"><div className="atlas-v2-inspector__role"><span>ROLE</span><p>{component.role}</p></div><dl>{component.metadata.map(([k,v])=><div key={k}><dt>{k}</dt><dd className={k==="STATE"?"state-value":""}>{v}</dd></div>)}</dl></div><footer><span>RELATED</span><RelatedLinks items={component.related}/></footer></aside>
      </div><div className="atlas-management-path"><div><span>MANAGEMENT PATH</span><strong>SERVER VALIDATED / CLIENT ENROLLMENT PENDING</strong></div><ol aria-label="Atlas management path"><li>{managementPath[0].name}</li><li aria-hidden="true">→</li><li>{managementPath[1].name}</li></ol></div><div className="atlas-trace-controls"><button onClick={()=>setLens("system")} aria-pressed={lens==="system"}>SYSTEM</button><button onClick={()=>setLens("ingestion")} aria-pressed={lens==="ingestion"}>TRACE INGESTION</button><button onClick={()=>setLens("search")} aria-pressed={lens==="search"}>TRACE DISTRIBUTED SEARCH</button></div><p className="sr-only">Windows Event Logs flow through Universal Forwarder on JNNSN to 127.0.0.1:9997 and atlas-indexer:9997. atlas-search-head coordinates distributed search with atlas-indexer over HTTPS port 8089 on atlas-network. The Rocky Linux Deployment Server is validated; management enrollment of the Universal Forwarder remains pending and is not active.</p></section>
      <section id="decision-trail" className="atlas-v2-section atlas-record-section"><header><p>03 / DECISION TRAIL</p><h2>Why Atlas was built this way</h2><span>Page-specific decision IDs cross-link architecture, proof, and troubleshooting.</span></header><div className="decision-trail">{atlasDecisionsV2.map(d=><article id={d.id.toLowerCase()} key={d.id}><div><b>{d.id}</b><h3>{d.title}</h3></div><dl><div><dt>CONTEXT</dt><dd>{d.context}</dd></div><div><dt>DECISION</dt><dd>{d.decision}</dd></div><div><dt>RATIONALE</dt><dd>{d.rationale}</dd></div>{"tradeoff" in d&&<div><dt>TRADE-OFF</dt><dd>{d.tradeoff}</dd></div>}{"validation" in d&&<div><dt>VALIDATION</dt><dd>{d.validation}</dd></div>}</dl><RelatedLinks items={d.related}/></article>)}</div></section>
      <section id="validation" className="atlas-v2-section atlas-record-section"><header><p>04 / VALIDATION</p><h2>Claims connected to proof</h2><span>Captured results are point-in-time observations, not live metrics.</span></header><div className="validation-chains">{validationMilestones.map(milestone=><article key={milestone.id}><b>MILESTONE {milestone.id}{"planned" in milestone&&milestone.planned?` · ${projectState.currentMilestone.status.toUpperCase()}`:""}</b><h3>{milestone.title}</h3><ol>{milestone.steps.map(step=><li key={step}>{step}</li>)}</ol><RelatedLinks items={milestone.related}/></article>)}</div><div className="evidence-exhibits">{evidence}</div></section>
      <section id="field-notes" className="atlas-v2-section atlas-record-section"><header><p>05 / FIELD NOTES</p><h2>Troubleshooting record</h2><span>Concise operational lessons; full detail remains in the engineering journals.</span></header><div className="field-notes">{fieldNotes.map(n=><article id={n.id.toLowerCase()} key={n.id}><b>{n.id} · RESOLVED</b><h3>{n.title}</h3><dl><div><dt>OBSERVED</dt><dd>{n.observed}</dd></div><div><dt>CAUSE</dt><dd>{n.cause}</dd></div><div><dt>RESOLUTION</dt><dd>{n.resolution}</dd></div><div><dt>LESSON</dt><dd>{n.lesson}</dd></div></dl><RelatedLinks items={n.related}/></article>)}</div></section>
      <section id="limitations" className="atlas-v2-section atlas-record-section"><header><p>06 / LIMITATIONS</p><h2>Explicit system boundaries</h2><span>Planned and exploratory work is not presented as implemented.</span></header><dl className="limitations-list">{limitationsV2.map(([name,state])=><div key={name}><dt>{name}</dt><dd>{state}</dd></div>)}</dl></section>
      <section id="source-of-truth" className="atlas-v2-section atlas-source"><p>07 / SOURCE OF TRUTH</p><h2>Independent verification starts with the repository.</h2><p>Atlas is documented publicly through source, configuration, architecture records, engineering journals, evidence, and commit history.</p><ul><li>Infrastructure</li><li>Architecture documentation</li><li>Engineering journal</li><li>Milestone records</li><li>Evidence artifacts</li><li>Configuration and Git history</li></ul><a href="https://github.com/jannsenagustin/resumeops" target="_blank" rel="noopener noreferrer">EXPLORE REPOSITORY →</a></section>
    </div>
  </main><ResumeViewer /></>;
}
