// Generated by scripts/generate-evidence-image-registry.mjs. Do not edit manually.
import type { StaticImageData } from "next/image";
import evidenceImage001 from "../docs/evidence/milestone-01-first-containerized-deployment/m01-atlas-indexer-container-health-01.png";
import evidenceImage002 from "../docs/evidence/milestone-01-first-containerized-deployment/m01-atlas-indexer-web-login-01.png";
import evidenceImage003 from "../docs/evidence/milestone-01-first-containerized-deployment/m01-docker-runtime-state-01.png";
import evidenceImage004 from "../docs/evidence/milestone-02-search-head/m02-atlas-search-head-web-login-01.png";
import evidenceImage005 from "../docs/evidence/milestone-02-search-head/m02-docker-container-health-01.png";
import evidenceImage006 from "../docs/evidence/milestone-02-search-head/m02-docker-multi-service-state-01.png";
import evidenceImage007 from "../docs/evidence/milestone-03-distributed-search/m03-atlas-indexer-search-peer-01.png";
import evidenceImage008 from "../docs/evidence/milestone-03-distributed-search/m03-atlas-search-head-distributed-search-01.png";
import evidenceImage009 from "../docs/evidence/milestone-03-distributed-search/m03-atlas-search-head-job-inspector-01.png";
import evidenceImage010 from "../docs/evidence/milestone-04-windows-event-ingestion/m04-atlas-indexer-receiver-connectivity-01.png";
import evidenceImage011 from "../docs/evidence/milestone-04-windows-event-ingestion/m04-atlas-search-head-job-inspector-01.png";
import evidenceImage012 from "../docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-event-ingestion-01.png";
import evidenceImage013 from "../docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-forwarding-status-01.png";
import evidenceImage014 from "../docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-service-status-01.png";
import evidenceImage015 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-admin-tools-01.png";
import evidenceImage016 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-admin-tools-02.png";
import evidenceImage017 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-cpu-allocation-01.png";
import evidenceImage018 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-default-route-01.png";
import evidenceImage019 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-dns-resolution-01.png";
import evidenceImage020 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-host-identity-01.png";
import evidenceImage021 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-internet-connectivity-01.png";
import evidenceImage022 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-kernel-version-01.png";
import evidenceImage023 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-memory-allocation-01.png";
import evidenceImage024 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-os-version-01.png";
import evidenceImage025 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-package-update-01.png";
import evidenceImage026 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-storage-layout-01.png";
import evidenceImage027 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-time-sync-01.png";
import evidenceImage028 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-first-start-01.png";
import evidenceImage029 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-rpm-installation-01.png";
import evidenceImage030 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-systemd-runtime-01.png";
import evidenceImage031 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-cli-status-01.png";
import evidenceImage032 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-management-port-01.png";
import evidenceImage033 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-runtime-identity-01.png";
import evidenceImage034 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-systemd-health-01.png";
import evidenceImage035 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-app-layout-01.png";
import evidenceImage036 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-configuration-01.png";
import evidenceImage037 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-server-reload-01.png";
import evidenceImage038 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-004-windows-deployment-client-config-01.png";
import evidenceImage039 from "../docs/evidence/milestone-05-data-ingestion/m05-atl-004-windows-deployment-app-installation-01.png";

export const atlasEvidenceImages: Readonly<Record<string, StaticImageData>> = {
  "docs/evidence/milestone-01-first-containerized-deployment/m01-atlas-indexer-container-health-01.png": evidenceImage001,
  "docs/evidence/milestone-01-first-containerized-deployment/m01-atlas-indexer-web-login-01.png": evidenceImage002,
  "docs/evidence/milestone-01-first-containerized-deployment/m01-docker-runtime-state-01.png": evidenceImage003,
  "docs/evidence/milestone-02-search-head/m02-atlas-search-head-web-login-01.png": evidenceImage004,
  "docs/evidence/milestone-02-search-head/m02-docker-container-health-01.png": evidenceImage005,
  "docs/evidence/milestone-02-search-head/m02-docker-multi-service-state-01.png": evidenceImage006,
  "docs/evidence/milestone-03-distributed-search/m03-atlas-indexer-search-peer-01.png": evidenceImage007,
  "docs/evidence/milestone-03-distributed-search/m03-atlas-search-head-distributed-search-01.png": evidenceImage008,
  "docs/evidence/milestone-03-distributed-search/m03-atlas-search-head-job-inspector-01.png": evidenceImage009,
  "docs/evidence/milestone-04-windows-event-ingestion/m04-atlas-indexer-receiver-connectivity-01.png": evidenceImage010,
  "docs/evidence/milestone-04-windows-event-ingestion/m04-atlas-search-head-job-inspector-01.png": evidenceImage011,
  "docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-event-ingestion-01.png": evidenceImage012,
  "docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-forwarding-status-01.png": evidenceImage013,
  "docs/evidence/milestone-04-windows-event-ingestion/m04-windows-uf-service-status-01.png": evidenceImage014,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-admin-tools-01.png": evidenceImage015,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-admin-tools-02.png": evidenceImage016,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-cpu-allocation-01.png": evidenceImage017,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-default-route-01.png": evidenceImage018,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-dns-resolution-01.png": evidenceImage019,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-host-identity-01.png": evidenceImage020,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-internet-connectivity-01.png": evidenceImage021,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-kernel-version-01.png": evidenceImage022,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-memory-allocation-01.png": evidenceImage023,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-os-version-01.png": evidenceImage024,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-package-update-01.png": evidenceImage025,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-storage-layout-01.png": evidenceImage026,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-001-rocky-time-sync-01.png": evidenceImage027,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-first-start-01.png": evidenceImage028,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-rpm-installation-01.png": evidenceImage029,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-002-rocky-splunk-systemd-runtime-01.png": evidenceImage030,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-cli-status-01.png": evidenceImage031,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-management-port-01.png": evidenceImage032,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-runtime-identity-01.png": evidenceImage033,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-splunk-systemd-health-01.png": evidenceImage034,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-app-layout-01.png": evidenceImage035,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-configuration-01.png": evidenceImage036,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-003-rocky-deployment-server-reload-01.png": evidenceImage037,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-004-windows-deployment-client-config-01.png": evidenceImage038,
  "docs/evidence/milestone-05-data-ingestion/m05-atl-004-windows-deployment-app-installation-01.png": evidenceImage039,
};
