[install]
state = enabled

[package]
check_for_updates = false

[ui]
is_visible = false
label = TA Atlas Demo Inputs

[launcher]
author = Jannsen Agustin
description = Centrally managed demo input for Project Atlas
version = 1.0.1
